version: "3.8"

services:
  web:
    env_file: .env
    container_name: ${SERVICE_PREFIX}-spa
    user: '1000:1000'
    build:
      context: ./docker
      args:
        CLEAN_YARN_CACHE: "true"
        ENABLE_TYPESCRIPT: ${ENABLE_TYPESCRIPT}
        HOST: ${VUE_UI_HOST}
        PROJECT_PATH: ${PROJECT_PATH}
        NODE_VERSION: ${NODE_VERSION}
    networks:
      local:
        aliases:
          - ${NETWORK}
    ports:
      - ${VUE_UI_PORT}:${VUE_UI_PORT}
      - ${APP_PORT}:8080
    volumes:
      - ${APP_PATH_HOST}:${PROJECT_PATH}
    # Override Dockerfile default command
    command: [ "vue", "ui", "--headless", "--port", "${VUE_UI_PORT}", "--host", "${VUE_UI_HOST}" ]

# Docker networks
networks:
  local:
    driver: bridge
    name: ${NETWORK}
